package com.vasmarfas.card.tools.developer

import com.vasmarfas.card.resources.*
import org.jetbrains.compose.resources.StringResource

data class MimeType(val type: String, val extensions: List<String>, val description: StringResource) {
    val category: String get() = type.substringBefore('/')
}

object MimeTypes {
    private fun m(type: String, extensions: String, description: StringResource) = MimeType(type, extensions.split(' '), description)

    val all: List<MimeType> = listOf(
        m("text/plain", "txt log conf ini", Res.string.mime_desc_txt),
        m("text/html", "html htm", Res.string.mime_desc_html),
        m("text/css", "css", Res.string.mime_desc_css),
        m("text/javascript", "js mjs", Res.string.mime_desc_js),
        m("text/csv", "csv", Res.string.mime_desc_csv),
        m("text/tab-separated-values", "tsv", Res.string.mime_desc_tsv),
        m("text/markdown", "md markdown", Res.string.mime_desc_md),
        m("text/calendar", "ics ical", Res.string.mime_desc_ics),
        m("text/vcard", "vcf", Res.string.mime_desc_vcf),
        m("text/vtt", "vtt", Res.string.mime_desc_vtt),
        m("text/x-python", "py", Res.string.mime_desc_py),
        m("text/x-java-source", "java", Res.string.mime_desc_java),
        m("text/x-kotlin", "kt kts", Res.string.mime_desc_kt),
        m("text/x-c", "c h", Res.string.mime_desc_c),
        m("text/x-c++", "cpp cc hpp", Res.string.mime_desc_cpp),
        m("text/x-go", "go", Res.string.mime_desc_go),
        m("text/x-rust", "rs", Res.string.mime_desc_rs),
        m("text/x-ruby", "rb", Res.string.mime_desc_rb),
        m("text/x-sh", "sh bash", Res.string.mime_desc_sh),
        m("text/event-stream", "", Res.string.mime_desc_event_stream),
        m("application/json", "json map", Res.string.mime_desc_json),
        m("application/ld+json", "jsonld", Res.string.mime_desc_jsonld),
        m("application/x-ndjson", "ndjson jsonl", Res.string.mime_desc_ndjson),
        m("application/xml", "xml xsd", Res.string.mime_desc_xml),
        m("application/xhtml+xml", "xhtml", Res.string.mime_desc_xhtml),
        m("application/atom+xml", "atom", Res.string.mime_desc_atom),
        m("application/rss+xml", "rss", Res.string.mime_desc_rss),
        m("application/xslt+xml", "xslt xsl", Res.string.mime_desc_xslt),
        m("application/yaml", "yaml yml", Res.string.mime_desc_yaml),
        m("application/toml", "toml", Res.string.mime_desc_toml),
        m("application/sql", "sql", Res.string.mime_desc_sql),
        m("application/graphql", "graphql gql", Res.string.mime_desc_graphql),
        m("application/x-www-form-urlencoded", "", Res.string.mime_desc_form_urlencoded),
        m("multipart/form-data", "", Res.string.mime_desc_form_data),
        m("application/octet-stream", "bin dat", Res.string.mime_desc_bin),
        m("application/pdf", "pdf", Res.string.mime_desc_pdf),
        m("application/rtf", "rtf", Res.string.mime_desc_rtf),
        m("application/msword", "doc dot", Res.string.mime_desc_doc),
        m("application/vnd.openxmlformats-officedocument.wordprocessingml.document", "docx", Res.string.mime_desc_docx),
        m("application/vnd.ms-excel", "xls", Res.string.mime_desc_xls),
        m("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "xlsx", Res.string.mime_desc_xlsx),
        m("application/vnd.ms-powerpoint", "ppt", Res.string.mime_desc_ppt),
        m("application/vnd.openxmlformats-officedocument.presentationml.presentation", "pptx", Res.string.mime_desc_pptx),
        m("application/vnd.visio", "vsd", Res.string.mime_desc_vsd),
        m("application/x-msaccess", "mdb accdb", Res.string.mime_desc_mdb),
        m("application/vnd.oasis.opendocument.text", "odt", Res.string.mime_desc_odt),
        m("application/vnd.oasis.opendocument.spreadsheet", "ods", Res.string.mime_desc_ods),
        m("application/vnd.oasis.opendocument.presentation", "odp", Res.string.mime_desc_odp),
        m("application/vnd.apple.pages", "pages", Res.string.mime_desc_pages),
        m("application/vnd.apple.numbers", "numbers", Res.string.mime_desc_numbers),
        m("application/vnd.apple.keynote", "key", Res.string.mime_desc_key),
        m("application/epub+zip", "epub", Res.string.mime_desc_epub),
        m("application/x-mobipocket-ebook", "mobi prc", Res.string.mime_desc_mobi),
        m("application/vnd.amazon.ebook", "azw azw3", Res.string.mime_desc_azw),
        m("image/vnd.djvu", "djvu djv", Res.string.mime_desc_djvu),
        m("application/vnd.ms-xpsdocument", "xps", Res.string.mime_desc_xps),
        m("application/postscript", "ps eps ai", Res.string.mime_desc_ps),
        m("image/png", "png", Res.string.mime_desc_png),
        m("image/apng", "apng", Res.string.mime_desc_apng),
        m("image/jpeg", "jpg jpeg jpe", Res.string.mime_desc_jpg),
        m("image/gif", "gif", Res.string.mime_desc_gif),
        m("image/webp", "webp", Res.string.mime_desc_webp),
        m("image/avif", "avif", Res.string.mime_desc_avif),
        m("image/jxl", "jxl", Res.string.mime_desc_jxl),
        m("image/svg+xml", "svg svgz", Res.string.mime_desc_svg),
        m("image/bmp", "bmp", Res.string.mime_desc_bmp),
        m("image/tiff", "tif tiff", Res.string.mime_desc_tif),
        m("image/heic", "heic", Res.string.mime_desc_heic),
        m("image/heif", "heif", Res.string.mime_desc_heif),
        m("image/vnd.microsoft.icon", "ico", Res.string.mime_desc_ico),
        m("image/vnd.adobe.photoshop", "psd", Res.string.mime_desc_psd),
        m("image/x-xcf", "xcf", Res.string.mime_desc_xcf),
        m("image/vnd.dwg", "dwg", Res.string.mime_desc_dwg),
        m("image/vnd.dxf", "dxf", Res.string.mime_desc_dxf),
        m("audio/mpeg", "mp3", Res.string.mime_desc_mp3),
        m("audio/wav", "wav", Res.string.mime_desc_wav),
        m("audio/ogg", "ogg oga", Res.string.mime_desc_ogg),
        m("audio/opus", "opus", Res.string.mime_desc_opus),
        m("audio/flac", "flac", Res.string.mime_desc_flac),
        m("audio/aac", "aac", Res.string.mime_desc_aac),
        m("audio/mp4", "m4a", Res.string.mime_desc_m4a),
        m("audio/webm", "weba", Res.string.mime_desc_weba),
        m("audio/midi", "mid midi", Res.string.mime_desc_mid),
        m("audio/aiff", "aif aiff", Res.string.mime_desc_aif),
        m("audio/amr", "amr", Res.string.mime_desc_amr),
        m("audio/x-ms-wma", "wma", Res.string.mime_desc_wma),
        m("audio/x-mpegurl", "m3u", Res.string.mime_desc_m3u),
        m("video/mp4", "mp4 m4v", Res.string.mime_desc_mp4),
        m("video/webm", "webm", Res.string.mime_desc_webm),
        m("video/x-matroska", "mkv", Res.string.mime_desc_mkv),
        m("video/quicktime", "mov qt", Res.string.mime_desc_mov),
        m("video/x-msvideo", "avi", Res.string.mime_desc_avi),
        m("video/mpeg", "mpeg mpg", Res.string.mime_desc_mpeg),
        m("video/ogg", "ogv", Res.string.mime_desc_ogv),
        m("video/3gpp", "3gp", Res.string.mime_desc_3gp),
        m("video/mp2t", "ts", Res.string.mime_desc_ts),
        m("video/x-flv", "flv", Res.string.mime_desc_flv),
        m("video/x-ms-wmv", "wmv", Res.string.mime_desc_wmv),
        m("application/vnd.apple.mpegurl", "m3u8", Res.string.mime_desc_m3u8),
        m("application/dash+xml", "mpd", Res.string.mime_desc_mpd),
        m("application/x-subrip", "srt", Res.string.mime_desc_srt),
        m("application/ttml+xml", "ttml", Res.string.mime_desc_ttml),
        m("font/woff", "woff", Res.string.mime_desc_woff),
        m("font/woff2", "woff2", Res.string.mime_desc_woff2),
        m("font/ttf", "ttf", Res.string.mime_desc_ttf),
        m("font/otf", "otf", Res.string.mime_desc_otf),
        m("application/vnd.ms-fontobject", "eot", Res.string.mime_desc_eot),
        m("application/zip", "zip", Res.string.mime_desc_zip),
        m("application/gzip", "gz tgz", Res.string.mime_desc_gz),
        m("application/x-tar", "tar", Res.string.mime_desc_tar),
        m("application/x-7z-compressed", "7z", Res.string.mime_desc_7z),
        m("application/vnd.rar", "rar", Res.string.mime_desc_rar),
        m("application/x-bzip2", "bz2", Res.string.mime_desc_bz2),
        m("application/x-xz", "xz", Res.string.mime_desc_xz),
        m("application/zstd", "zst", Res.string.mime_desc_zst),
        m("application/java-archive", "jar", Res.string.mime_desc_jar),
        m("application/vnd.android.package-archive", "apk", Res.string.mime_desc_apk),
        m("application/x-apple-diskimage", "dmg", Res.string.mime_desc_dmg),
        m("application/x-iso9660-image", "iso", Res.string.mime_desc_iso),
        m("application/vnd.debian.binary-package", "deb", Res.string.mime_desc_deb),
        m("application/x-rpm", "rpm", Res.string.mime_desc_rpm),
        m("application/x-msi", "msi", Res.string.mime_desc_msi),
        m("application/vnd.microsoft.portable-executable", "exe dll", Res.string.mime_desc_exe),
        m("application/x-chrome-extension", "crx", Res.string.mime_desc_crx),
        m("application/x-xpinstall", "xpi", Res.string.mime_desc_xpi),
        m("application/wasm", "wasm", Res.string.mime_desc_wasm),
        m("application/manifest+json", "webmanifest", Res.string.mime_desc_webmanifest),
        m("application/x-shockwave-flash", "swf", Res.string.mime_desc_swf),
        m("application/x-httpd-php", "php", Res.string.mime_desc_php),
        m("application/x-bittorrent", "torrent", Res.string.mime_desc_torrent),
        m("application/pkix-cert", "cer crt der", Res.string.mime_desc_cer),
        m("application/x-pem-file", "pem", Res.string.mime_desc_pem),
        m("application/x-pkcs12", "p12 pfx", Res.string.mime_desc_p12),
        m("application/pgp-encrypted", "pgp gpg", Res.string.mime_desc_pgp),
        m("application/pgp-signature", "asc sig", Res.string.mime_desc_asc),
        m("application/gpx+xml", "gpx", Res.string.mime_desc_gpx),
        m("application/vnd.google-earth.kml+xml", "kml", Res.string.mime_desc_kml),
        m("application/vnd.google-earth.kmz", "kmz", Res.string.mime_desc_kmz),
        m("application/geo+json", "geojson", Res.string.mime_desc_geojson),
        m("model/stl", "stl", Res.string.mime_desc_stl),
        m("model/obj", "obj", Res.string.mime_desc_obj),
        m("model/gltf+json", "gltf", Res.string.mime_desc_gltf),
        m("model/gltf-binary", "glb", Res.string.mime_desc_glb),
        m("model/3mf", "3mf", Res.string.mime_desc_3mf),
        m("model/step", "step stp", Res.string.mime_desc_step),
        m("model/vnd.usdz+zip", "usdz", Res.string.mime_desc_usdz),
        m("application/vnd.sqlite3", "sqlite db sqlite3", Res.string.mime_desc_sqlite),
        m("application/vnd.apache.parquet", "parquet", Res.string.mime_desc_parquet),
        m("application/vnd.comicbook+zip", "cbz", Res.string.mime_desc_cbz),
        m("application/vnd.comicbook-rar", "cbr", Res.string.mime_desc_cbr),
        m("message/rfc822", "eml mht", Res.string.mime_desc_eml),
        m("application/x-abiword", "abw", Res.string.mime_desc_abw),
        m("application/vnd.wordperfect", "wpd", Res.string.mime_desc_wpd),
    )

    fun search(query: String): List<MimeType> {
        val q = query.trim().lowercase().removePrefix(".").removePrefix("*.")
        if (q.isEmpty()) return all
        val byExtension = all.filter { t -> t.extensions.any { it == q } }
        if (byExtension.isNotEmpty()) return byExtension
        return all.filter { t ->
            t.type.contains(q) || t.description.matches(q) || t.extensions.any { it.startsWith(q) }
        }
    }
}
